/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CardAppendItem: typeof import('./src/components/base/card-append-item.vue')['default']
    CardState: typeof import('./src/components/base/card-state.vue')['default']
    CardTitle: typeof import('./src/components/base/card-title.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DynamicComponents: typeof import('./src/components/dynamic-components.vue')['default']
    HaButton: typeof import('./src/components/ha-button/ha-button.vue')['default']
    HaDialog: typeof import('./src/components/ha-dialog/ha-dialog.vue')['default']
    PrependCardIcon: typeof import('./src/components/base/prepend-card-icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
  }
}
