name: 'HA - Dashboard'
description: 'My first real add-on!'
version: '0.0.0'
slug: 'ha-dashboard'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  80/tcp: 8081
  443/tcp: 8082
map:
  - ssl
  - share
