name: 'HA - Dashboard'
description: 'My first real add-on!'
version: '0.0.0'
slug: 'ha-dashboard'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8081/tcp: 80
  8082/tcp: 443
map:
  - ssl
  - share
