name: 'HA - Dashboard'
description: 'My first real add-on!'
version: '0.0.0'
slug: 'ha-dashboard'
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  4173/tcp: 4173
